# Generated by Django 3.2.9 on 2022-08-18 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom05', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='launch_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
